In [1]:
import torch

In [18]:
m,n = 10,12

W_rank = 2
W = torch.randn((m,W_rank)) @ torch.randn((W_rank,n))
print(W,W.shape)

tensor([[-4.6877e-01,  2.5729e+00, -2.5917e+00,  3.5412e+00,  1.9687e+00,
         -1.8502e+00,  9.4551e-01, -7.5330e-01, -1.5584e+00, -5.3848e-01,
         -4.0354e-02, -2.9194e+00],
        [-9.0276e-01,  1.6961e-01,  4.4553e-01, -2.1456e+00,  1.2184e-01,
          6.5123e-01, -6.8133e-01, -6.8898e-01,  2.9163e-01,  3.2086e-02,
         -1.1398e+00,  8.5507e-02],
        [-7.4850e-01, -1.2966e-01,  6.7647e-01, -2.2853e+00, -1.0624e-01,
          7.7798e-01, -7.0623e-01, -5.2822e-01,  4.2778e-01,  8.6988e-02,
         -1.0050e+00,  3.9328e-01],
        [-2.7324e+00,  1.7801e+00, -9.0630e-02, -4.1209e+00,  1.3401e+00,
          8.5553e-01, -1.3998e+00, -2.2870e+00,  1.1039e-02, -1.8589e-01,
         -3.1688e+00, -1.2521e+00],
        [-2.6910e-01,  1.4583e+00, -1.4666e+00,  1.9979e+00,  1.1158e+00,
         -1.0457e+00,  5.3303e-01, -4.2947e-01, -8.8178e-01, -3.0495e-01,
         -2.7304e-02, -1.6536e+00],
        [-1.0689e-03,  4.4212e-01, -5.0155e-01,  8.2542e-01,  3.3902e-01,
      

: 

In [8]:
import numpy as np

W_rank_ = np.linalg.matrix_rank(W)
W_rank_

np.int64(2)

: 

## Singular Value Decomposition

In [16]:
U,S,V = torch.svd(W)

print(U,U.shape,np.linalg.matrix_rank(U))


tensor([[ 3.0641e-01, -4.9802e-01,  5.2590e-01,  1.8979e-01, -4.1581e-01,
          3.7730e-01, -1.4300e-01,  4.0598e-02, -8.2578e-02, -3.6417e-02],
        [-1.5042e-01, -3.8087e-01,  1.2237e-01,  4.5390e-01,  7.6214e-01,
          1.0835e-01,  1.1341e-01, -7.5379e-02, -1.2378e-02, -5.2286e-03],
        [-2.1010e-01, -8.1748e-02, -7.0182e-02, -4.4413e-02,  1.1172e-01,
         -2.3772e-02, -9.4032e-01,  1.0323e-01,  1.8364e-01, -2.5679e-02],
        [-2.7968e-01, -5.8903e-02,  4.7613e-01,  1.7874e-01, -1.5983e-01,
         -6.9589e-01,  7.0153e-02,  1.4038e-01,  2.0663e-01,  2.8727e-01],
        [-5.1704e-01,  2.9001e-01,  3.9463e-01, -1.6701e-01, -2.3454e-02,
          4.6087e-01,  1.0349e-01, -2.7848e-01,  3.9906e-01, -6.6909e-02],
        [ 8.0693e-02, -7.4292e-04, -1.6175e-01,  4.2745e-03,  1.1194e-02,
          2.7855e-01, -1.2679e-02,  1.6202e-02,  1.1726e-01,  9.3564e-01],
        [-3.4279e-01, -5.5338e-01, -1.2737e-02, -6.9448e-01,  6.3167e-02,
         -2.2430e-02,  1.3212e-0

: 

In [17]:
print(V,V.shape,np.linalg.matrix_rank(V))

tensor([[ 0.1294,  0.0361, -0.9466,  0.1366,  0.1078,  0.2063, -0.0634,  0.0306,
         -0.0456,  0.0668],
        [ 0.1211, -0.1227,  0.0782, -0.2881, -0.3144,  0.4797,  0.0405, -0.3872,
         -0.3214,  0.5133],
        [-0.0727,  0.4599,  0.0983,  0.0956,  0.4211,  0.0830,  0.0401, -0.3272,
         -0.1356,  0.2176],
        [ 0.1364, -0.1465,  0.0637,  0.0155, -0.2382,  0.3129, -0.3218,  0.3280,
         -0.1141, -0.0730],
        [-0.3409,  0.1286, -0.0995, -0.3009,  0.2723, -0.1372, -0.2558, -0.2687,
          0.1686,  0.1471],
        [ 0.5203, -0.0479,  0.1549, -0.1806,  0.4242,  0.0100, -0.5884,  0.1629,
          0.1170,  0.1627],
        [-0.4457, -0.0618, -0.1303, -0.2041, -0.2267, -0.4256, -0.3360,  0.2760,
         -0.2695,  0.3574],
        [ 0.0790,  0.3667, -0.0119,  0.1333, -0.3469, -0.0959, -0.4902, -0.3971,
         -0.2808, -0.4632],
        [ 0.3392, -0.5382, -0.0920, -0.0125,  0.1110, -0.5130,  0.1065, -0.3925,
         -0.2716, -0.0396],
        [ 0.3403,  

: 

In [19]:
print(S,S.shape,np.linalg.matrix_rank(S))

tensor([1.6140e+01, 5.9043e+00, 6.8701e-07, 3.7265e-07, 3.2264e-07, 1.6079e-07,
        8.8218e-08, 6.5367e-08, 4.2559e-08, 1.4638e-08]) torch.Size([10]) 1


: 

In [ ]:
U_r = U[:,W_rank]
S_r = 

: 